package com.example.nextstepz.notifications.data.repository

import android.util.Log
import com.example.nextstepz.notifications.data.model.NotificationCategory
import com.example.nextstepz.notifications.data.model.NotificationItem
import com.example.nextstepz.notifications.data.model.NotificationOutcome
import com.example.nextstepz.notifications.data.remote.NotificationDto
import com.example.nextstepz.notifications.data.remote.NotificationSupabaseClient

/**
 * Reads / updates the Supabase `notifications` table for the signed-in user.
 * Notifications themselves are generated by database triggers when statuses
 * change in job_applications / *_reports / jobs / employers.
 */
class NotificationRepository {

    private val api = NotificationSupabaseClient.api

    suspend fun getNotifications(userId: String): List<NotificationItem> =
        api.getNotifications(userId = "eq.$userId").map { it.toItem() }

    suspend fun getUnreadCount(userId: String): Int =
        api.getUnread(userId = "eq.$userId").size

    suspend fun markAsRead(id: String): Boolean = try {
        api.markRead(id = "eq.$id", body = mapOf("is_read" to true)).isSuccessful
    } catch (e: Exception) {
        Log.e(TAG, "markAsRead error", e); false
    }

    suspend fun markAllRead(userId: String): Boolean = try {
        api.markAllRead(
            userId = "eq.$userId",
            isRead = "eq.false",
            body = mapOf("is_read" to true),
        ).isSuccessful
    } catch (e: Exception) {
        Log.e(TAG, "markAllRead error", e); false
    }

    companion object {
        private const val TAG = "NotificationRepository"
    }
}

private fun NotificationDto.toItem() = NotificationItem(
    id = id.toString(),
    category = NotificationCategory.fromKey(category),
    outcome = when (outcome?.lowercase()) {
        "positive" -> NotificationOutcome.POSITIVE
        "negative" -> NotificationOutcome.NEGATIVE
        else -> NotificationOutcome.NEUTRAL
    },
    title = title ?: "Thông báo",
    message = message ?: "",
    isRead = isRead ?: false,
    timeLabel = formatTime(createdAt),
)

/** "2026-06-21T16:51:30.31+00:00" -> "16:51 · 21/06/2026" (UTC, no java.time dep). */
private fun formatTime(iso: String?): String {
    if (iso.isNullOrBlank()) return ""
    return try {
        val date = iso.substringBefore('T')          // 2026-06-21
        val time = iso.substringAfter('T').take(5)    // 16:51
        val parts = date.split("-")
        if (parts.size == 3) "$time · ${parts[2]}/${parts[1]}/${parts[0]}" else iso
    } catch (e: Exception) {
        iso
    }
}
